### ISSUE TITLE
problem with rails 4.2

### ISSUE THREAD

**Issue by mathieujobin** [mathieujobin/render_component#1]
while this works fine with rails 4.1.8
it does not with rails 4.2

I am getting this error

```
undefined method `redirect_url' for #<ActionDispatch::Response::RackBody:0x0000000895c808>
```

at 
https://github.com/somekool/render_component/blob/master/lib/render_component/components.rb?#L54
